Update README.md
editorconfig/specification pull request #36
Opened 2023-01-01 07:57 UTC by Youssef1313

2023-01-01 18:29 UTC, cxw42 approved these changes

2023-01-01 18:35 UTC, cxw42 commented
Thanks for the contribution!  Looks good to me; I just want to hear back from @xuhdev in https://github.com/editorconfig/editorconfig/issues/360#issuecomment-1368505205 before merging since I wasn't part of the `spec.editorconfig.org` discussion.

2023-01-02 06:39 UTC, xuhdev requested changes

2023-01-02 06:39 UTC, xuhdev commented on README.md
> +available at <https://spec.editorconfig.org/>.
I don't think this will display properly with `<>`. Could you remove them?

2023-01-02 06:40 UTC, xuhdev approved these changes

2023-01-02 06:40 UTC, xuhdev commented on README.md
> +available at <https://spec.editorconfig.org/>.
nvm, thought this was the website

2023-01-02 06:41 UTC, merged

2023-01-02 06:41 UTC, xuhdev commented
Thank you for your contribution!